### PR TITLE
added SSH_AUTH_SOCK env var, known_hosts symlink

### PR DESCRIPTION
**Pull request by ivoba**
- added SSH_AUTH_SOCK env var to enable access to private repos  
  somebody on OSX please test this with dlite and docker-machine, works on linux
- added symlink for known_hosts to container
- added .composer as volume to share composer cache

### CODE REVIEW

**Comment by gherkins** [comment]
seems not to work on OSX/dlite yet. 🙍 

it mounts the authsock as an empty directory, although it's a file on the host system.
You'll need sudo to access ist, though...

**Comment by gherkins** [comment]
is $SSH_AUTH_SOCK a folder in linux?
Can you even mount a single file w/ docker compose?

```
 ~ > sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.4
BuildVersion:   15E65

 ~ > echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.xxxxxx/Listeners

 ~ > ls -al $SSH_AUTH_SOCK
srw-rw-rw-  1 max  wheel  0 14 Mai 11:09 /private/tmp/com.apple.launchd.xxxxxx/Listeners


```

**Comment by ivoba** [comment]
AFAIK $SSH_AUTH_SOCK is a single file and mounting a single file should be possible

srwxrwxr-x 1 ivo ivo 0 Mai 17 09:07 /run/user/1000/keyring-NBm0uU/ssh  

Not sure how the situation is on Windows.

**Comment by ivoba** [comment]
seems not to work cross platform,
we used a different approach of copying the ssh folder in the container

**Pull request closed without merging**
