### PR TITLE
added ssh keys & known_hosts as volumes

### PR DESCRIPTION
**Pull request by ivoba**
added ssh keys & known_hosts as volumes to enable access to private repos

### CODE REVIEW

**Comment by gherkins** [comment]
maybe rather mount the whole .ssh folder?
`id_rsa` could be `id_psa` or something else. Or someone might use different keys for different hosts and have  a `.ssh/config` file

**Comment by ivoba** [comment]
yes would better, but we would need to chown the .ssh folder.  
currently i get: 

> Bad owner or permissions on /var/www/.ssh/config

since .ssh has this rights in the container:

> drwx------  2 www-data 1000 4096 Feb 13 13:51 .ssh/

we could chown or chmod the folder in the container

**Comment by gherkins** [comment]
i think mounting the whole .ssh folder and chown it to www-data would be an ok workaround for now, what do you think? 
at least that also gives you the config and multiple keys inside the container...

**Comment by ivoba** [comment]
yes, this probably the most practical and cross-plattform solution.  

I tried to mount it as volume but the chown command did also change the owner on the host.  
This should be avoided.  
Also i think the .ssh folder should be mounted readonly.

We could also copy it with `docker cp`  i think in a dev setup this would be ok.

**Comment by gherkins** [comment]
do we still need this, since https://github.com/nerdpress-org/docker-sf3/pull/29 copies the whole folder?

**Comment by ivoba** [comment]
no, can be closed

**Pull request merged**
